nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['*']
            allow-headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST']
            max_age: 3600
        '^/api/*': 
            allow_origin: ['*']
            allow-headers: ['Content-Type', 'Authorization']
            allow_methods: ['*']
            max_age: 3600
